### ISSUE TITLE
A None type code results in AttributeError

### ISSUE THREAD

**Issue by kumar303** [andymckay/mobile-codes#1]
The docs say that unknown values result in KeyError so this should be fixed to raise a KeyError instead:

```
mobile_codes.mcc(None)
....
Traceback (most recent call last):
  ...
    country = mobile_codes.mcc(mcc)
  File "/Users/kumar/.virtualenvs/webpay/lib/python2.7/site-packages/mobile_codes/__init__.py", line 2013, in _get
    return _cache[var][':'.join(k.upper() for k in codes)]
  File "/Users/kumar/.virtualenvs/webpay/lib/python2.7/site-packages/mobile_codes/__init__.py", line 2013, in <genexpr>
    return _cache[var][':'.join(k.upper() for k in codes)]
AttributeError: 'NoneType' object has no attribute 'upper'
```

**Comment by andymckay** [comment]
I don't intend to maintain this library anymore. I've added a note to the readme and sending this comment to people who have an issue on the library so you can fork it or do whatever you'd like.
